---
title: "HW 01 - Airbnb listings in Edinburgh"
author: "Jieming Xiao"
date: "07/12/2022"
output: github_document
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(dsbox)
library(ggplot2)
```

## Exercises

### Exercise 1

There are 13,245 rows in the dataset.

### Exercise 2

Each row represents a listing of properties.


### Exercise 3



```{r prices-neighbourhoods}
ggplot(data = edibnb, mapping = aes(x = price)) +
  geom_histogram(binwidth = 500) +
  facet_wrap(~neighbourhood)
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r top-5-median}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-plot}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-summary-stats}
# remove this comment and add the code for Exercise 4 here
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r review-scores-rating}
# remove this comment and add the code for Exercise 5 here
```
